const CHARACTERS = ['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9'] as const;
const DOTS = ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9'] as const;
const BAMBOOS = ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9'] as const;
const HONORS = ['east', 'south', 'west', 'north', 'red', 'green', 'white'] as const;
const FLOWERS = [
  'spring',
  'summer',
  'autumn',
  'winter',
  'plum',
  'orchid',
  'bamboo',
  'chrysanthemum',
] as const;
const ENABLED_TILES = [...CHARACTERS, ...DOTS, ...BAMBOOS, ...HONORS, ...FLOWERS] as const;

export const COMMON_SIMPLE_PATTERN_FACTS = [
  ['bigFourWinds', '大四喜', 88, true],
  ['bigThreeDragons', '大三元', 88, true],
  ['allGreen', '绿一色', 88, true],
  ['nineGates', '九莲宝灯', 88, true],
  ['fourKongs', '四杠', 88, true],
  ['sevenShiftedPairs', '连七对', 88, true],
  ['thirteenOrphans', '十三幺', 88, true],
  ['allTerminals', '清幺九', 64, true],
  ['littleFourWinds', '小四喜', 64, true],
  ['littleThreeDragons', '小三元', 64, true],
  ['allHonors', '字一色', 64, true],
  ['fourConcealedPungs', '四暗刻', 64, true],
  ['pureTerminalChows', '一色双龙会', 64, true],
  ['quadrupleChow', '一色四同顺', 48, true],
  ['fourPureShiftedPungs', '一色四节高', 48, true],
  ['fourPureShiftedChows', '一色四步高', 32, true],
  ['threeKongs', '三杠', 32, true],
  ['allTerminalsAndHonors', '混幺九', 32, true],
  ['sevenPairs', '七对', 24, true],
  ['greaterHonorsAndKnittedTiles', '七星不靠', 24, false],
  ['allEvenPungs', '全双刻', 24, true],
  ['fullFlush', '清一色', 24, true],
  ['pureTripleChow', '一色三同顺', 24, true],
  ['pureShiftedPungs', '一色三节高', 24, true],
  ['upperTiles', '全大', 24, true],
  ['middleTiles', '全中', 24, true],
  ['lowerTiles', '全小', 24, true],
  ['pureStraight', '清龙', 16, true],
  ['threeSuitedTerminalChows', '三色双龙会', 16, true],
  ['pureShiftedChows', '一色三步高', 16, true],
  ['allFives', '全带五', 16, true],
  ['triplePung', '三同刻', 16, true],
  ['threeConcealedPungs', '三暗刻', 16, true],
  ['lesserHonorsAndKnittedTiles', '全不靠', 12, false],
  ['knittedStraight', '组合龙', 12, false],
  ['upperFour', '大于五', 12, true],
  ['lowerFour', '小于五', 12, true],
  ['bigThreeWinds', '三风刻', 12, true],
  ['mixedStraight', '花龙', 8, true],
  ['reversibleTiles', '推不倒', 8, true],
  ['mixedTripleChow', '三色三同顺', 8, true],
  ['mixedShiftedPungs', '三色三节高', 8, true],
  ['chickenHand', '无番和', 8, true],
  ['lastTileDraw', '妙手回春', 8, true],
  ['lastTileClaim', '海底捞月', 8, true],
  ['outWithReplacementTile', '杠上开花', 8, true],
  ['robbingTheKong', '抢杠和', 8, true],
  ['allPungs', '碰碰和', 6, true],
  ['halfFlush', '混一色', 6, true],
  ['mixedShiftedChows', '三色三步高', 6, true],
  ['allTypes', '五门齐', 6, true],
  ['meldedHand', '全求人', 6, true],
  ['twoConcealedKongs', '双暗杠', 6, true],
  ['twoDragonPungs', '双箭刻', 6, true],
  ['outsideHand', '全带幺', 4, true],
  ['fullyConcealedHand', '不求人', 4, true],
  ['twoMeldedKongs', '双明杠', 4, true],
  ['lastTile', '和绝张', 4, true],
  ['dragonPung', '箭刻', 2, true],
  ['prevalentWind', '圈风刻', 2, true],
  ['seatWind', '门风刻', 2, true],
  ['concealedHand', '门前清', 2, true],
  ['allChows', '平和', 2, true],
  ['tileHog', '四归一', 2, true],
  ['doublePung', '双同刻', 2, true],
  ['twoConcealedPungs', '双暗刻', 2, true],
  ['concealedKong', '暗杠', 2, true],
  ['allSimples', '断幺', 2, true],
  ['pureDoubleChow', '一般高', 1, true],
  ['mixedDoubleChow', '喜相逢', 1, true],
  ['shortStraight', '连六', 1, true],
  ['twoTerminalChows', '老少副', 1, true],
  ['pungOfTerminalsOrHonors', '幺九刻', 1, true],
  ['meldedKong', '明杠', 1, true],
  ['oneVoidedSuit', '缺一门', 1, true],
  ['noHonors', '无字', 1, true],
  ['edgeWait', '边张', 1, true],
  ['closedWait', '坎张', 1, true],
  ['singleWait', '单钓将', 1, true],
  ['selfDrawn', '自摸', 1, true],
  ['flowerTiles', '花牌', 1, true],
] as const;

const ENABLED_PATTERN_FACTS = COMMON_SIMPLE_PATTERN_FACTS.filter(([, , , enabled]) => enabled);
export const COMMON_SIMPLE_UNSUPPORTED_PATTERN_FACTS = {
  greaterHonorsAndKnittedTiles: 'seven-star-unrelated',
  lesserHonorsAndKnittedTiles: 'all-unrelated',
  knittedStraight: 'knitted-straight',
} as const;

const PATTERNS = COMMON_SIMPLE_PATTERN_FACTS.map(([patternId, name, value, enabled]) => ({
  patternId,
  name,
  recognizerKey: `recognizer.${patternId}`,
  ...(!enabled
    ? {
        recognizerParams: {
          requiredStructureKey: COMMON_SIMPLE_UNSUPPORTED_PATTERN_FACTS[patternId],
        },
      }
    : {}),
  value,
  unit: 'fan',
  enabled,
  sourceRefs: ['SRC-A01'],
  confidence: 'high',
}));

const STRUCTURE_CAPABILITIES = [
  'structure.standard',
  'structure.sevenPairs',
  'structure.thirteenOrphans',
] as const;
const SCORING_CAPABILITIES = [
  'scoring.additive',
  'scoring.extra.context-match',
  'scoring.extra.tile-group-count',
] as const;
const RECOGNIZER_CAPABILITIES = ENABLED_PATTERN_FACTS.map(
  ([patternId]) => `recognizer.${patternId}`,
);

export const COMMON_SIMPLE_CAPABILITY_DEFINITIONS = [
  ...STRUCTURE_CAPABILITIES.map((capabilityKey) => ({ capabilityKey, kind: 'structure' as const })),
  ...SCORING_CAPABILITIES.map((capabilityKey) => ({ capabilityKey, kind: 'scoring' as const })),
  ...RECOGNIZER_CAPABILITIES.map((capabilityKey) => ({
    capabilityKey,
    kind: 'recognizer' as const,
  })),
] as const;

const WIND_OPTIONS = [
  { value: 'east', labelKey: 'winds.east' },
  { value: 'south', labelKey: 'winds.south' },
  { value: 'west', labelKey: 'winds.west' },
  { value: 'north', labelKey: 'winds.north' },
] as const;

const PATTERN_ADJUSTMENTS = ENABLED_PATTERN_FACTS.flatMap(([patternId]) => [
  {
    adjustmentId: `pattern.${patternId}.enabled`,
    target: { module: 'pattern' as const, patternId, field: 'enabled' as const },
    valueConstraint: { valueType: 'boolean' as const },
  },
  {
    adjustmentId: `pattern.${patternId}.value`,
    target: { module: 'pattern' as const, patternId, field: 'value' as const },
    valueConstraint: { valueType: 'number' as const, minimum: 0 },
  },
]);

const maxCopies = Object.fromEntries(
  ENABLED_TILES.map((tile) => [tile, FLOWERS.includes(tile as (typeof FLOWERS)[number]) ? 1 : 4]),
);

const rulePackageData = {
  schemaVersion: 1,
  manifest: {
    ruleId: 'common-simple',
    ruleVersion: '1.0.0',
    displayName: '大众麻将·通用简化版',
    familyId: 'common-mahjong',
    region: 'general',
    status: 'test',
    recommended: true,
    engineCompatibility: {
      minEngineVersion: '0.0.0',
      requiredCapabilities: [
        ...STRUCTURE_CAPABILITIES,
        ...SCORING_CAPABILITIES,
        ...RECOGNIZER_CAPABILITIES,
      ],
    },
    releasedAt: '2026-08-10T00:00:00.000Z',
    contentHash: 'f3325572e156585de7fcf5ce17041644886b6ca0cdc37ff40ad9931a45307cb8',
  },
  tileSet: {
    enabledTiles: ENABLED_TILES,
    maxCopies,
    groups: [
      { id: 'characters', labelKey: 'tiles.characters', tiles: CHARACTERS },
      { id: 'dots', labelKey: 'tiles.dots', tiles: DOTS },
      { id: 'bamboos', labelKey: 'tiles.bamboos', tiles: BAMBOOS },
      { id: 'honors', labelKey: 'tiles.honors', tiles: HONORS },
      { id: 'flowers', labelKey: 'tiles.flowers', tiles: FLOWERS },
    ],
  },
  handModel: {
    targetStructuralTileCount: 14,
    readyStructuralTileCount: 13,
    requiredMeldCount: 4,
    allowedMeldTypes: ['chow', 'pung', 'open-kong', 'concealed-kong'],
    maxDeclaredMelds: 4,
    flowerPolicy: 'separate',
  },
  structures: [
    {
      structureKey: 'standard-meld-pair',
      capabilityKey: 'structure.standard',
      enabled: true,
      supportStatus: 'SUPPORTED',
    },
    {
      structureKey: 'seven-pairs',
      capabilityKey: 'structure.sevenPairs',
      enabled: true,
      supportStatus: 'SUPPORTED',
      parameters: {
        requiredPairCount: 7,
        quadHandling: 'TWO_PAIRS',
      },
    },
    {
      structureKey: 'thirteen-orphans',
      capabilityKey: 'structure.thirteenOrphans',
      enabled: true,
      supportStatus: 'SUPPORTED',
      parameters: {
        requiredTiles: [
          'm1',
          'm9',
          'p1',
          'p9',
          's1',
          's9',
          'east',
          'south',
          'west',
          'north',
          'red',
          'green',
          'white',
        ],
        duplicateTileCount: 2,
      },
    },
    {
      structureKey: 'seven-star-unrelated',
      enabled: false,
      supportStatus: 'NOT_SUPPORTED_IN_V0_1',
      reasonCode: 'STRUCTURE_NOT_IMPLEMENTED',
    },
    {
      structureKey: 'all-unrelated',
      enabled: false,
      supportStatus: 'NOT_SUPPORTED_IN_V0_1',
      reasonCode: 'STRUCTURE_NOT_IMPLEMENTED',
    },
    {
      structureKey: 'knitted-straight',
      enabled: false,
      supportStatus: 'NOT_SUPPORTED_IN_V0_1',
      reasonCode: 'STRUCTURE_NOT_IMPLEMENTED',
    },
  ],
  contexts: [
    {
      contextId: 'seatWind',
      labelKey: 'context.seatWind',
      valueType: 'single-select',
      required: true,
      displayGroup: 'primary',
      applicableWinModes: ['discard', 'self-draw'],
      options: WIND_OPTIONS,
    },
    {
      contextId: 'roundWind',
      labelKey: 'context.roundWind',
      valueType: 'single-select',
      required: true,
      displayGroup: 'primary',
      applicableWinModes: ['discard', 'self-draw'],
      options: WIND_OPTIONS,
    },
    {
      contextId: 'afterKongReplacement',
      labelKey: 'context.afterKongReplacement',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['self-draw'],
      displayWhen: { winModes: ['self-draw'] },
    },
    {
      contextId: 'robbingAddedKong',
      labelKey: 'context.robbingAddedKong',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['discard'],
      displayWhen: { winModes: ['discard'] },
    },
    {
      contextId: 'wallLastDraw',
      labelKey: 'context.wallLastDraw',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['self-draw'],
      displayWhen: { winModes: ['self-draw'] },
    },
    {
      contextId: 'lastDiscardAfterWallExhausted',
      labelKey: 'context.lastDiscardAfterWallExhausted',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['discard'],
      displayWhen: { winModes: ['discard'] },
    },
    {
      contextId: 'lastTile',
      labelKey: 'context.lastTile',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['discard', 'self-draw'],
    },
  ],
  patterns: PATTERNS,
  relations: [
    { type: 'covers', winner: 'bigFourWinds', covered: 'bigThreeWinds' },
    { type: 'covers', winner: 'bigFourWinds', covered: 'prevalentWind' },
    { type: 'covers', winner: 'bigFourWinds', covered: 'seatWind' },
    { type: 'covers', winner: 'bigFourWinds', covered: 'allPungs' },
    { type: 'covers', winner: 'bigThreeDragons', covered: 'twoDragonPungs' },
    { type: 'covers', winner: 'bigThreeDragons', covered: 'dragonPung' },
    { type: 'covers', winner: 'littleThreeDragons', covered: 'twoDragonPungs' },
    { type: 'covers', winner: 'littleThreeDragons', covered: 'dragonPung' },
    { type: 'covers', winner: 'fourKongs', covered: 'threeKongs' },
    { type: 'covers', winner: 'fourKongs', covered: 'twoMeldedKongs' },
    { type: 'covers', winner: 'fourKongs', covered: 'twoConcealedKongs' },
    { type: 'covers', winner: 'fourKongs', covered: 'meldedKong' },
    { type: 'covers', winner: 'fourKongs', covered: 'concealedKong' },
    { type: 'covers', winner: 'sevenShiftedPairs', covered: 'sevenPairs' },
    { type: 'covers', winner: 'thirteenOrphans', covered: 'allTypes' },
    { type: 'covers', winner: 'thirteenOrphans', covered: 'concealedHand' },
    { type: 'covers', winner: 'thirteenOrphans', covered: 'singleWait' },
    { type: 'covers', winner: 'fourConcealedPungs', covered: 'threeConcealedPungs' },
    { type: 'covers', winner: 'fourConcealedPungs', covered: 'twoConcealedPungs' },
    { type: 'covers', winner: 'fourConcealedPungs', covered: 'allPungs' },
    { type: 'covers', winner: 'pureTerminalChows', covered: 'fullFlush' },
    { type: 'covers', winner: 'pureTerminalChows', covered: 'allChows' },
    { type: 'covers', winner: 'pureTerminalChows', covered: 'twoTerminalChows' },
    { type: 'covers', winner: 'pureTerminalChows', covered: 'pureDoubleChow' },
    { type: 'covers', winner: 'quadrupleChow', covered: 'pureTripleChow' },
    { type: 'covers', winner: 'quadrupleChow', covered: 'pureDoubleChow' },
    { type: 'covers', winner: 'fourPureShiftedPungs', covered: 'pureShiftedPungs' },
    { type: 'covers', winner: 'fourPureShiftedPungs', covered: 'allPungs' },
    { type: 'covers', winner: 'threeKongs', covered: 'twoMeldedKongs' },
    { type: 'covers', winner: 'threeKongs', covered: 'twoConcealedKongs' },
    { type: 'covers', winner: 'threeKongs', covered: 'meldedKong' },
    { type: 'covers', winner: 'threeKongs', covered: 'concealedKong' },
    { type: 'covers', winner: 'sevenPairs', covered: 'concealedHand' },
    { type: 'covers', winner: 'sevenPairs', covered: 'singleWait' },
    { type: 'covers', winner: 'fullFlush', covered: 'oneVoidedSuit' },
    { type: 'covers', winner: 'fullFlush', covered: 'noHonors' },
    { type: 'covers', winner: 'allEvenPungs', covered: 'allPungs' },
    { type: 'covers', winner: 'allEvenPungs', covered: 'allSimples' },
    { type: 'covers', winner: 'upperTiles', covered: 'upperFour' },
    { type: 'covers', winner: 'middleTiles', covered: 'allSimples' },
    { type: 'covers', winner: 'lowerTiles', covered: 'lowerFour' },
    { type: 'covers', winner: 'fullyConcealedHand', covered: 'selfDrawn' },
    { type: 'covers', winner: 'fullyConcealedHand', covered: 'concealedHand' },
    { type: 'covers', winner: 'twoConcealedKongs', covered: 'concealedKong' },
    { type: 'covers', winner: 'twoMeldedKongs', covered: 'meldedKong' },
    { type: 'covers', winner: 'twoDragonPungs', covered: 'dragonPung' },
    {
      type: 'mutually-exclusive',
      patterns: ['edgeWait', 'closedWait', 'singleWait'],
      resolution: 'explicit-priority',
      priority: ['singleWait', 'closedWait', 'edgeWait'],
    },
  ],
  scoring: {
    strategyKey: 'scoring.additive',
    unit: 'fan',
    parameters: {},
    cap: { enabled: false, value: null },
    extras: [
      {
        extraId: 'selfDraw',
        calculatorKey: 'scoring.extra.context-match',
        parameters: { patternId: 'selfDrawn', contextId: 'winMode', equals: 'self-draw' },
        mode: 'ADD',
        value: 1,
        capPlacement: 'before-cap',
      },
      {
        extraId: 'flowers',
        calculatorKey: 'scoring.extra.tile-group-count',
        parameters: { patternId: 'flowerTiles', tileGroupId: 'flowers' },
        mode: 'ADD',
        value: 1,
        capPlacement: 'before-cap',
      },
    ],
  },
  legality: {
    minimumFan: 0,
    onMissingRequiredContext: 'incomplete-context',
  },
  temporaryAdjustments: [
    {
      adjustmentId: 'minimumFan',
      target: { module: 'legality', field: 'minimumFan' },
      valueConstraint: { valueType: 'number', minimum: 0 },
    },
    {
      adjustmentId: 'cap.enabled',
      target: { module: 'scoring-cap', field: 'enabled' },
      valueConstraint: { valueType: 'boolean' },
    },
    {
      adjustmentId: 'cap.value',
      target: { module: 'scoring-cap', field: 'value' },
      valueConstraint: { valueType: 'nullable-number', minimum: 0 },
    },
    {
      adjustmentId: 'selfDraw.mode',
      target: { module: 'scoring-extra', extraId: 'selfDraw', field: 'mode' },
      valueConstraint: { valueType: 'enum', values: ['ADD'] },
    },
    {
      adjustmentId: 'selfDraw.value',
      target: { module: 'scoring-extra', extraId: 'selfDraw', field: 'value' },
      valueConstraint: { valueType: 'number', minimum: 0 },
    },
    ...PATTERN_ADJUSTMENTS,
  ],
  encyclopedia: {
    ruleId: 'common-simple',
    ruleVersion: '1.0.0',
    intro: [],
    patternArticles: [],
    examples: [],
    sourceArticles: [],
    knownLimitations: [],
  },
  sources: [
    {
      sourceId: 'SRC-A01',
      title: '中国麻将竞赛规则',
      publisher: '国家体育总局审定规则公开转载',
      url: 'https://mahjong-ca.org/wp-content/uploads/2019/07/mjgz060510.pdf',
      sourceType: 'official',
      note: '81 番体系、番型定义、番值与计分关系的规范性依据。',
    },
    {
      sourceId: 'SRC-B01',
      title: '腾讯欢乐麻将：大众麻将定位',
      publisher: '腾讯',
      url: 'https://majiang.qq.com/webplat/info/news_version3/7207/25932/25972/m16347/201611/523207.shtml',
      sourceType: 'corroborating',
      note: '大众玩法低门槛与国标番型主干的交叉依据。',
    },
    {
      sourceId: 'SRC-B02',
      title: '腾讯欢乐麻将：基本和牌介绍',
      publisher: '腾讯',
      url: 'https://majiang.qq.com/webplat/info/news_version3/7207/31873/31888/35514/m18795/201805/719437.shtml',
      sourceType: 'corroborating',
    },
    {
      sourceId: 'SRC-B03',
      title: '腾讯 TMT 番表',
      publisher: '腾讯',
      url: 'https://tmt.qq.com/act/a20150617hlmj/index.html',
      sourceType: 'corroborating',
    },
    {
      sourceId: 'SRC-B04',
      title: '联众大众麻将基本规则',
      publisher: '联众',
      url: 'https://www.ourgame.com/game/game-intro-new/h2g/mj2_002.html',
      sourceType: 'public-local-rule',
      note: '和牌结构与平台特有机制排除项的交叉依据。',
    },
    {
      sourceId: 'SRC-B05',
      title: '联众大众番种图例',
      publisher: '联众',
      url: 'https://www.ourgame.com/game/game-intro-new/h2g/mj2_004.html',
      sourceType: 'corroborating',
    },
  ],
} as const;

export const commonSimpleRulePackageInput: unknown = rulePackageData;
