const CHARACTERS = ['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9'] as const;
const DOTS = ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9'] as const;
const BAMBOOS = ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9'] as const;
const HONORS = ['east', 'south', 'west', 'north', 'red', 'green', 'white'] as const;
const FLOWERS = [
  'spring',
  'summer',
  'autumn',
  'winter',
  'plum',
  'orchid',
  'bamboo',
  'chrysanthemum',
] as const;
const ENABLED_TILES = [...CHARACTERS, ...DOTS, ...BAMBOOS, ...HONORS, ...FLOWERS] as const;

export const COMMON_SIMPLE_PATTERN_FACTS = [
  ['bigFourWinds', '大四喜', 88, true, '东南西北四副风刻或杠。'],
  ['bigThreeDragons', '大三元', 88, true, '中发白三副箭刻或杠。'],
  ['allGreen', '绿一色', 88, true, '仅由二、三、四、六、八条及发组成。'],
  ['nineGates', '九莲宝灯', 88, true, '门清同一花色满足 1112345678999 基本形，并和同花色任一张。'],
  ['fourKongs', '四杠', 88, true, '四副杠。'],
  ['sevenShiftedPairs', '连七对', 88, true, '同一花色七个连续序数对子。'],
  ['thirteenOrphans', '十三幺', 88, true, '十三种幺九字牌各一张，并以其中一种成对。'],
  ['allTerminals', '清幺九', 64, true, '仅由一、九序数牌的刻、杠及将组成。'],
  ['littleFourWinds', '小四喜', 64, true, '三副风刻或杠，第四种风作将。'],
  ['littleThreeDragons', '小三元', 64, true, '两副箭刻或杠，第三种箭牌作将。'],
  ['allHonors', '字一色', 64, true, '全部由风牌、箭牌组成。'],
  ['fourConcealedPungs', '四暗刻', 64, true, '四副暗刻或暗杠。'],
  ['pureTerminalChows', '一色双龙会', 64, true, '同花色两副 123、两副 789，5 作将。'],
  ['quadrupleChow', '一色四同顺', 48, true, '同花色四副相同顺子。'],
  ['fourPureShiftedPungs', '一色四节高', 48, true, '同花色四副依次递增一个序数的刻或杠。'],
  ['fourPureShiftedChows', '一色四步高', 32, true, '同花色四副依次递增一位或两位的顺子。'],
  ['threeKongs', '三杠', 32, true, '三副杠。'],
  ['allTerminalsAndHonors', '混幺九', 32, true, '仅由幺九序数牌与字牌组成的刻、杠及将。'],
  ['sevenPairs', '七对', 24, true, '七个对子。'],
  [
    'greaterHonorsAndKnittedTiles',
    '七星不靠',
    24,
    false,
    '国标特殊不靠结构；本版本结构能力暂不支持。',
  ],
  ['allEvenPungs', '全双刻', 24, true, '仅由二、四、六、八的刻、杠及将组成。'],
  ['fullFlush', '清一色', 24, true, '只使用一种序数花色，不含字牌。'],
  ['pureTripleChow', '一色三同顺', 24, true, '同花色三副相同顺子。'],
  ['pureShiftedPungs', '一色三节高', 24, true, '同花色三副依次递增一个序数的刻或杠。'],
  ['upperTiles', '全大', 24, true, '全部序数牌来自七、八、九。'],
  ['middleTiles', '全中', 24, true, '全部序数牌来自四、五、六。'],
  ['lowerTiles', '全小', 24, true, '全部序数牌来自一、二、三。'],
  ['pureStraight', '清龙', 16, true, '同花色包含 123、456、789。'],
  ['threeSuitedTerminalChows', '三色双龙会', 16, true, '两花色各有 123 与 789，第三花色 5 作将。'],
  ['pureShiftedChows', '一色三步高', 16, true, '同花色三副依次递增一位或两位的顺子。'],
  ['allFives', '全带五', 16, true, '每副面子与将都包含 5。'],
  ['triplePung', '三同刻', 16, true, '三种花色相同序数的三副刻或杠。'],
  ['threeConcealedPungs', '三暗刻', 16, true, '三副暗刻或暗杠。'],
  [
    'lesserHonorsAndKnittedTiles',
    '全不靠',
    12,
    false,
    '国标特殊不靠结构；本版本结构能力暂不支持。',
  ],
  [
    'knittedStraight',
    '组合龙',
    12,
    false,
    '三花色 147、258、369 错位组合形成特殊顺子；本版本结构能力暂不支持。',
  ],
  ['upperFour', '大于五', 12, true, '序数牌仅使用六至九。'],
  ['lowerFour', '小于五', 12, true, '序数牌仅使用一至四。'],
  ['bigThreeWinds', '三风刻', 12, true, '三副风刻或杠。'],
  ['mixedStraight', '花龙', 8, true, '三种花色的三副顺子组合成 123、456、789。'],
  ['reversibleTiles', '推不倒', 8, true, '仅由国标定义的上下图形无区别牌组成。'],
  ['mixedTripleChow', '三色三同顺', 8, true, '三种花色各一副相同序数顺子。'],
  ['mixedShiftedPungs', '三色三节高', 8, true, '三种花色依次递增序数的三副刻或杠。'],
  ['chickenHand', '无番和', 8, true, '除花牌外不存在其他可计番型。'],
  ['lastTileDraw', '妙手回春', 8, true, '自摸牌墙最后一张牌。'],
  ['lastTileClaim', '海底捞月', 8, true, '和牌墙摸完后的最后一张舍牌。'],
  ['outWithReplacementTile', '杠上开花', 8, true, '杠后补牌自摸和。'],
  ['robbingTheKong', '抢杠和', 8, true, '和他人加杠的牌。'],
  ['allPungs', '碰碰和', 6, true, '四副刻或杠加一对将。'],
  ['halfFlush', '混一色', 6, true, '一种序数花色与字牌组成。'],
  ['mixedShiftedChows', '三色三步高', 6, true, '三种花色依次递增的三副顺子。'],
  ['allTypes', '五门齐', 6, true, '万、筒、条、风、箭五类全部出现。'],
  ['meldedHand', '全求人', 6, true, '四副面子均为吃、碰或明杠，单钓他人舍牌和。'],
  ['twoConcealedKongs', '双暗杠', 6, true, '两副暗杠。'],
  ['twoDragonPungs', '双箭刻', 6, true, '两副箭刻或杠。'],
  ['outsideHand', '全带幺', 4, true, '每副面子及将都含幺九牌或字牌。'],
  ['fullyConcealedHand', '不求人', 4, true, '无吃、碰、明杠并自摸和。'],
  ['twoMeldedKongs', '双明杠', 4, true, '两副明杠。'],
  ['lastTile', '和绝张', 4, true, '和到同种四张中其余三张均已明见的最后一张。'],
  ['dragonPung', '箭刻', 2, true, '中、发、白任一刻或杠。'],
  ['prevalentWind', '圈风刻', 2, true, '圈风刻或杠。'],
  ['seatWind', '门风刻', 2, true, '门风刻或杠。'],
  ['concealedHand', '门前清', 2, true, '无吃、碰、明杠，以点和方式和牌。'],
  ['allChows', '平和', 2, true, '四副顺子、序数牌作将，且不是边张、坎张或单钓将。'],
  ['tileHog', '四归一', 2, true, '四张相同牌分别用于非杠组合。'],
  ['doublePung', '双同刻', 2, true, '两种花色相同序数的两副刻或杠。'],
  ['twoConcealedPungs', '双暗刻', 2, true, '两副暗刻或暗杠。'],
  ['concealedKong', '暗杠', 2, true, '一副暗杠。'],
  ['allSimples', '断幺', 2, true, '不含一、九及字牌。'],
  ['pureDoubleChow', '一般高', 1, true, '同花色两副相同顺子。'],
  ['mixedDoubleChow', '喜相逢', 1, true, '两种花色相同序数顺子。'],
  ['shortStraight', '连六', 1, true, '同花色两副顺子组成连续六张序数。'],
  ['twoTerminalChows', '老少副', 1, true, '同花色 123 与 789。'],
  ['pungOfTerminalsOrHonors', '幺九刻', 1, true, '一、九或不属于圈风、门风的风牌刻或杠。'],
  ['meldedKong', '明杠', 1, true, '一副明杠。'],
  ['oneVoidedSuit', '缺一门', 1, true, '只使用两种序数花色，可含字牌。'],
  ['noHonors', '无字', 1, true, '不含风牌、箭牌。'],
  ['edgeWait', '边张', 1, true, '只以 3 和 12，或 7 和 89 构成单一顺子等待。'],
  ['closedWait', '坎张', 1, true, '只等顺子中间张。'],
  ['singleWait', '单钓将', 1, true, '只等将牌。'],
  ['selfDrawn', '自摸', 1, true, '自摸和牌。'],
  ['flowerTiles', '花牌', 1, true, '每张花牌计 1 番。'],
] as const;

const ENABLED_PATTERN_FACTS = COMMON_SIMPLE_PATTERN_FACTS.filter(([, , , enabled]) => enabled);
export const COMMON_SIMPLE_UNSUPPORTED_PATTERN_FACTS = {
  greaterHonorsAndKnittedTiles: 'seven-star-unrelated',
  lesserHonorsAndKnittedTiles: 'all-unrelated',
  knittedStraight: 'knitted-straight',
} as const;

const PATTERNS = COMMON_SIMPLE_PATTERN_FACTS.map(([patternId, name, value, enabled]) => ({
  patternId,
  name,
  recognizerKey: `recognizer.${patternId}`,
  ...(!enabled
    ? {
        recognizerParams: {
          requiredStructureKey: COMMON_SIMPLE_UNSUPPORTED_PATTERN_FACTS[patternId],
        },
      }
    : {}),
  value,
  unit: 'fan',
  enabled,
  sourceRefs: ['SRC-A01'],
  confidence: 'high',
}));

const PATTERN_ARTICLES = COMMON_SIMPLE_PATTERN_FACTS.map(([patternId, , , , definition]) => ({
  patternId,
  blocks: [{ type: 'paragraph' as const, text: definition }],
}));

const STRUCTURE_CAPABILITIES = [
  'structure.standard',
  'structure.sevenPairs',
  'structure.thirteenOrphans',
] as const;
const SCORING_CAPABILITIES = [
  'scoring.additive',
  'scoring.extra.context-match',
  'scoring.extra.tile-group-count',
] as const;
const RECOGNIZER_CAPABILITIES = ENABLED_PATTERN_FACTS.map(
  ([patternId]) => `recognizer.${patternId}`,
);

export const COMMON_SIMPLE_CAPABILITY_DEFINITIONS = [
  ...STRUCTURE_CAPABILITIES.map((capabilityKey) => ({ capabilityKey, kind: 'structure' as const })),
  ...SCORING_CAPABILITIES.map((capabilityKey) => ({ capabilityKey, kind: 'scoring' as const })),
  ...RECOGNIZER_CAPABILITIES.map((capabilityKey) => ({
    capabilityKey,
    kind: 'recognizer' as const,
  })),
] as const;

const WIND_OPTIONS = [
  { value: 'east', labelKey: 'winds.east' },
  { value: 'south', labelKey: 'winds.south' },
  { value: 'west', labelKey: 'winds.west' },
  { value: 'north', labelKey: 'winds.north' },
] as const;

const PATTERN_ADJUSTMENTS = ENABLED_PATTERN_FACTS.flatMap(([patternId]) => [
  {
    adjustmentId: `pattern.${patternId}.enabled`,
    target: { module: 'pattern' as const, patternId, field: 'enabled' as const },
    valueConstraint: { valueType: 'boolean' as const },
  },
  {
    adjustmentId: `pattern.${patternId}.value`,
    target: { module: 'pattern' as const, patternId, field: 'value' as const },
    valueConstraint: { valueType: 'number' as const, minimum: 0 },
  },
]);

const maxCopies = Object.fromEntries(
  ENABLED_TILES.map((tile) => [tile, FLOWERS.includes(tile as (typeof FLOWERS)[number]) ? 1 : 4]),
);

const SOURCES = [
  {
    sourceId: 'SRC-A01',
    title: '中国麻将竞赛规则',
    publisher: '国家体育总局审定规则公开转载',
    url: 'https://mahjong-ca.org/wp-content/uploads/2019/07/mjgz060510.pdf',
    sourceType: 'official',
    note: '81 番体系、番型定义、番值与计分关系的规范性依据。',
  },
  {
    sourceId: 'SRC-B01',
    title: '腾讯欢乐麻将：大众麻将定位',
    publisher: '腾讯',
    url: 'https://majiang.qq.com/webplat/info/news_version3/7207/25932/25972/m16347/201611/523207.shtml',
    sourceType: 'corroborating',
    note: '大众玩法低门槛与国标番型主干的交叉依据。',
  },
  {
    sourceId: 'SRC-B02',
    title: '腾讯欢乐麻将：基本和牌介绍',
    publisher: '腾讯',
    url: 'https://majiang.qq.com/webplat/info/news_version3/7207/31873/31888/35514/m18795/201805/719437.shtml',
    sourceType: 'corroborating',
    note: '大众麻将基本和牌方式的公开说明。',
  },
  {
    sourceId: 'SRC-B03',
    title: '腾讯 TMT 番表',
    publisher: '腾讯',
    url: 'https://tmt.qq.com/act/a20150617hlmj/index.html',
    sourceType: 'corroborating',
    note: '国标式番型体系的辅助交叉证据，不引入赛事扩展规则。',
  },
  {
    sourceId: 'SRC-B04',
    title: '联众大众麻将基本规则',
    publisher: '联众',
    url: 'https://www.ourgame.com/game/game-intro-new/h2g/mj2_002.html',
    sourceType: 'public-local-rule',
    note: '和牌结构与平台特有机制排除项的交叉依据。',
  },
  {
    sourceId: 'SRC-B05',
    title: '联众大众番种图例',
    publisher: '联众',
    url: 'https://www.ourgame.com/game/game-intro-new/h2g/mj2_004.html',
    sourceType: 'corroborating',
    note: '大众番型体系与花牌内容的交叉依据，不引入会员番种等平台扩展。',
  },
] as const;

const rulePackageData = {
  schemaVersion: 1,
  manifest: {
    ruleId: 'common-simple',
    ruleVersion: '1.0.0',
    displayName: '大众麻将·通用简化版',
    familyId: 'common-mahjong',
    region: 'general',
    status: 'test',
    recommended: true,
    engineCompatibility: {
      minEngineVersion: '0.0.0',
      requiredCapabilities: [
        ...STRUCTURE_CAPABILITIES,
        ...SCORING_CAPABILITIES,
        ...RECOGNIZER_CAPABILITIES,
      ],
    },
    releasedAt: '2026-08-10T00:00:00.000Z',
    contentHash: '4f53c21eb71e5a0b5b007f345adf0d31e09a9a8ebca9f4cb21959553c16cfd2c',
  },
  tileSet: {
    enabledTiles: ENABLED_TILES,
    maxCopies,
    groups: [
      { id: 'characters', labelKey: 'tiles.characters', tiles: CHARACTERS },
      { id: 'dots', labelKey: 'tiles.dots', tiles: DOTS },
      { id: 'bamboos', labelKey: 'tiles.bamboos', tiles: BAMBOOS },
      { id: 'honors', labelKey: 'tiles.honors', tiles: HONORS },
      { id: 'flowers', labelKey: 'tiles.flowers', tiles: FLOWERS },
    ],
  },
  handModel: {
    targetStructuralTileCount: 14,
    readyStructuralTileCount: 13,
    requiredMeldCount: 4,
    allowedMeldTypes: ['chow', 'pung', 'open-kong', 'concealed-kong'],
    openKongPolicy: {
      distinction: 'undifferentiated',
      allowedKinds: ['direct', 'added'],
    },
    maxDeclaredMelds: 4,
    flowerPolicy: 'separate',
  },
  structures: [
    {
      structureKey: 'standard-meld-pair',
      capabilityKey: 'structure.standard',
      enabled: true,
      supportStatus: 'SUPPORTED',
    },
    {
      structureKey: 'seven-pairs',
      capabilityKey: 'structure.sevenPairs',
      enabled: true,
      supportStatus: 'SUPPORTED',
      parameters: {
        requiredPairCount: 7,
        quadHandling: 'TWO_PAIRS',
      },
    },
    {
      structureKey: 'thirteen-orphans',
      capabilityKey: 'structure.thirteenOrphans',
      enabled: true,
      supportStatus: 'SUPPORTED',
      parameters: {
        requiredTiles: [
          'm1',
          'm9',
          'p1',
          'p9',
          's1',
          's9',
          'east',
          'south',
          'west',
          'north',
          'red',
          'green',
          'white',
        ],
        duplicateTileCount: 2,
      },
    },
    {
      structureKey: 'seven-star-unrelated',
      enabled: false,
      supportStatus: 'NOT_SUPPORTED_IN_V0_1',
      reasonCode: 'STRUCTURE_NOT_IMPLEMENTED',
    },
    {
      structureKey: 'all-unrelated',
      enabled: false,
      supportStatus: 'NOT_SUPPORTED_IN_V0_1',
      reasonCode: 'STRUCTURE_NOT_IMPLEMENTED',
    },
    {
      structureKey: 'knitted-straight',
      enabled: false,
      supportStatus: 'NOT_SUPPORTED_IN_V0_1',
      reasonCode: 'STRUCTURE_NOT_IMPLEMENTED',
    },
  ],
  contexts: [
    {
      contextId: 'seatWind',
      labelKey: 'context.seatWind',
      valueType: 'single-select',
      required: true,
      displayGroup: 'primary',
      applicableWinModes: ['discard', 'self-draw'],
      options: WIND_OPTIONS,
    },
    {
      contextId: 'roundWind',
      labelKey: 'context.roundWind',
      valueType: 'single-select',
      required: true,
      displayGroup: 'primary',
      applicableWinModes: ['discard', 'self-draw'],
      options: WIND_OPTIONS,
    },
    {
      contextId: 'afterKongReplacement',
      labelKey: 'context.afterKongReplacement',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['self-draw'],
      displayWhen: { winModes: ['self-draw'] },
    },
    {
      contextId: 'robbingAddedKong',
      labelKey: 'context.robbingAddedKong',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['discard'],
      displayWhen: { winModes: ['discard'] },
    },
    {
      contextId: 'wallLastDraw',
      labelKey: 'context.wallLastDraw',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['self-draw'],
      displayWhen: { winModes: ['self-draw'] },
    },
    {
      contextId: 'lastDiscardAfterWallExhausted',
      labelKey: 'context.lastDiscardAfterWallExhausted',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['discard'],
      displayWhen: { winModes: ['discard'] },
    },
    {
      contextId: 'lastTile',
      labelKey: 'context.lastTile',
      valueType: 'boolean',
      required: false,
      displayGroup: 'more',
      applicableWinModes: ['discard', 'self-draw'],
    },
  ],
  patterns: PATTERNS,
  relations: [
    { type: 'covers', winner: 'bigFourWinds', covered: 'bigThreeWinds' },
    { type: 'covers', winner: 'bigFourWinds', covered: 'prevalentWind' },
    { type: 'covers', winner: 'bigFourWinds', covered: 'seatWind' },
    { type: 'covers', winner: 'bigFourWinds', covered: 'allPungs' },
    { type: 'covers', winner: 'bigThreeDragons', covered: 'twoDragonPungs' },
    { type: 'covers', winner: 'bigThreeDragons', covered: 'dragonPung' },
    { type: 'covers', winner: 'littleThreeDragons', covered: 'twoDragonPungs' },
    { type: 'covers', winner: 'littleThreeDragons', covered: 'dragonPung' },
    { type: 'covers', winner: 'fourKongs', covered: 'threeKongs' },
    { type: 'covers', winner: 'fourKongs', covered: 'twoMeldedKongs' },
    { type: 'covers', winner: 'fourKongs', covered: 'twoConcealedKongs' },
    { type: 'covers', winner: 'fourKongs', covered: 'meldedKong' },
    { type: 'covers', winner: 'fourKongs', covered: 'concealedKong' },
    { type: 'covers', winner: 'sevenShiftedPairs', covered: 'sevenPairs' },
    { type: 'covers', winner: 'thirteenOrphans', covered: 'allTypes' },
    { type: 'covers', winner: 'thirteenOrphans', covered: 'concealedHand' },
    { type: 'covers', winner: 'thirteenOrphans', covered: 'singleWait' },
    { type: 'covers', winner: 'fourConcealedPungs', covered: 'threeConcealedPungs' },
    { type: 'covers', winner: 'fourConcealedPungs', covered: 'twoConcealedPungs' },
    { type: 'covers', winner: 'fourConcealedPungs', covered: 'allPungs' },
    { type: 'covers', winner: 'pureTerminalChows', covered: 'fullFlush' },
    { type: 'covers', winner: 'pureTerminalChows', covered: 'allChows' },
    { type: 'covers', winner: 'pureTerminalChows', covered: 'twoTerminalChows' },
    { type: 'covers', winner: 'pureTerminalChows', covered: 'pureDoubleChow' },
    { type: 'covers', winner: 'quadrupleChow', covered: 'pureTripleChow' },
    { type: 'covers', winner: 'quadrupleChow', covered: 'pureDoubleChow' },
    { type: 'covers', winner: 'fourPureShiftedPungs', covered: 'pureShiftedPungs' },
    { type: 'covers', winner: 'fourPureShiftedPungs', covered: 'allPungs' },
    { type: 'covers', winner: 'threeKongs', covered: 'twoMeldedKongs' },
    { type: 'covers', winner: 'threeKongs', covered: 'twoConcealedKongs' },
    { type: 'covers', winner: 'threeKongs', covered: 'meldedKong' },
    { type: 'covers', winner: 'threeKongs', covered: 'concealedKong' },
    { type: 'covers', winner: 'sevenPairs', covered: 'concealedHand' },
    { type: 'covers', winner: 'sevenPairs', covered: 'singleWait' },
    { type: 'covers', winner: 'fullFlush', covered: 'oneVoidedSuit' },
    { type: 'covers', winner: 'fullFlush', covered: 'noHonors' },
    { type: 'covers', winner: 'allEvenPungs', covered: 'allPungs' },
    { type: 'covers', winner: 'allEvenPungs', covered: 'allSimples' },
    { type: 'covers', winner: 'upperTiles', covered: 'upperFour' },
    { type: 'covers', winner: 'middleTiles', covered: 'allSimples' },
    { type: 'covers', winner: 'lowerTiles', covered: 'lowerFour' },
    { type: 'covers', winner: 'fullyConcealedHand', covered: 'selfDrawn' },
    { type: 'covers', winner: 'fullyConcealedHand', covered: 'concealedHand' },
    { type: 'covers', winner: 'twoConcealedKongs', covered: 'concealedKong' },
    { type: 'covers', winner: 'twoMeldedKongs', covered: 'meldedKong' },
    { type: 'covers', winner: 'twoDragonPungs', covered: 'dragonPung' },
    {
      type: 'mutually-exclusive',
      patterns: ['edgeWait', 'closedWait', 'singleWait'],
      resolution: 'explicit-priority',
      priority: ['singleWait', 'closedWait', 'edgeWait'],
    },
  ],
  scoring: {
    strategyKey: 'scoring.additive',
    unit: 'fan',
    parameters: {},
    cap: { enabled: false, value: null },
    extras: [
      {
        extraId: 'selfDraw',
        calculatorKey: 'scoring.extra.context-match',
        parameters: { patternId: 'selfDrawn', contextId: 'winMode', equals: 'self-draw' },
        mode: 'ADD',
        value: 1,
        capPlacement: 'before-cap',
      },
      {
        extraId: 'flowers',
        calculatorKey: 'scoring.extra.tile-group-count',
        parameters: { patternId: 'flowerTiles', tileGroupId: 'flowers' },
        mode: 'ADD',
        value: 1,
        capPlacement: 'before-cap',
      },
    ],
  },
  legality: {
    minimumFan: 0,
    onMissingRequiredContext: 'incomplete-context',
  },
  temporaryAdjustments: [
    {
      adjustmentId: 'minimumFan',
      target: { module: 'legality', field: 'minimumFan' },
      valueConstraint: { valueType: 'number', minimum: 0 },
    },
    {
      adjustmentId: 'cap.enabled',
      target: { module: 'scoring-cap', field: 'enabled' },
      valueConstraint: { valueType: 'boolean' },
    },
    {
      adjustmentId: 'cap.value',
      target: { module: 'scoring-cap', field: 'value' },
      valueConstraint: { valueType: 'nullable-number', minimum: 0 },
    },
    {
      adjustmentId: 'selfDraw.mode',
      target: { module: 'scoring-extra', extraId: 'selfDraw', field: 'mode' },
      valueConstraint: { valueType: 'enum', values: ['ADD'] },
    },
    {
      adjustmentId: 'selfDraw.value',
      target: { module: 'scoring-extra', extraId: 'selfDraw', field: 'value' },
      valueConstraint: { valueType: 'number', minimum: 0 },
    },
    ...PATTERN_ADJUSTMENTS,
  ],
  encyclopedia: {
    ruleId: 'common-simple',
    ruleVersion: '1.0.0',
    intro: [
      {
        type: 'paragraph',
        text: '大众麻将·通用简化版是本产品维护的代表性通用预设，以广泛认知的中国麻将番型为主干，提供低门槛的单手牌番数计算。',
      },
      {
        type: 'list',
        items: [
          '结构合法即可和，最低起和门槛为 0 番。',
          '支持普通结构、七对和十三幺。',
          '不等同于完整国标麻将，也不等同于任何单一游戏平台的全部玩法。',
          '不包含庄家翻倍、房间倍数、虚拟资产或玩家间支付结算。',
        ],
      },
    ],
    patternArticles: PATTERN_ARTICLES,
    examples: [],
    sourceArticles: SOURCES.map(({ sourceId, note }) => ({
      sourceId,
      blocks: [{ type: 'paragraph', text: note }],
    })),
    knownLimitations: [
      {
        type: 'list',
        items: [
          'v0.1.0 暂不支持七星不靠、全不靠和组合龙三种特殊结构。',
          '当前支持状态为测试版，尚未标记为已完整支持。',
          '地方平台特有的庄家、加倍、奖励和结算规则不属于本预设。',
        ],
      },
    ],
  },
  sources: SOURCES,
} as const;

export const commonSimpleRulePackageInput: unknown = rulePackageData;
